/** Styles for IndianDivasSettleTab — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../styles/common';
import { colors, radius, spacing } from '../../theme';

export const styles = makeStyles({
  wrap: { gap: spacing(2) },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing(2),
  },
  headerText: { flex: 1, gap: 2 },
  title: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  sub: { color: colors.muted, fontSize: 12 },
  refreshBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
    backgroundColor: colors.surface,
  },
  refreshBtnText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  state: {
    minHeight: 140,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(1.5),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  emptyTitle: { color: colors.foreground, fontWeight: '700', fontSize: 14 },
  muted: { color: colors.muted, fontSize: 12, textAlign: 'center' },
  list: { gap: spacing(2), paddingBottom: spacing(1) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    gap: spacing(2),
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(1),
  },
  index: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  game: { flex: 1, color: colors.muted, fontSize: 12, textAlign: 'right' },
  txn: {
    color: colors.foreground,
    fontFamily: 'monospace',
    fontSize: 11,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(1),
    borderRadius: radius.sm,
  },
  stats: { flexDirection: 'row', gap: spacing(2) },
  stat: { flex: 1 },
  statLabel: {
    color: colors.muted,
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 2,
  },
  statValue: { color: colors.foreground, fontSize: 14, fontWeight: '700' },
  actions: { flexDirection: 'row', gap: spacing(1), flexWrap: 'wrap' },
  btn: {
    flex: 1,
    minWidth: 72,
    borderRadius: radius.sm,
    paddingVertical: 10,
    alignItems: 'center',
  },
  btnWin: { backgroundColor: '#16a34a' },
  btnLoss: { backgroundColor: '#dc2626' },
  btnRollback: { backgroundColor: '#f59e0b' },
  btnTextLight: { color: '#fff', fontWeight: '700', fontSize: 12 },
  btnTextDark: { color: '#111827', fontWeight: '700', fontSize: 12 },
  rollbackAll: {
    backgroundColor: '#dc2626',
    borderRadius: radius.sm,
    paddingVertical: 12,
    alignItems: 'center',
  },
  rollbackAllText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  disabled: { opacity: 0.5 },
  msg: { color: colors.muted, fontSize: 12 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    padding: spacing(4),
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing(4),
    gap: spacing(2),
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  formLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(2),
    color: colors.foreground,
    backgroundColor: colors.background,
  },
  modalActions: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(1) },
  modalBtn: {
    flex: 1,
    borderRadius: radius.sm,
    paddingVertical: 12,
    alignItems: 'center',
  },
  modalCancel: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
  },
});
