/** Styles for AAAFraudBetReportScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  sub: { color: colors.muted, fontSize: 12, marginTop: spacing(1), marginBottom: spacing(3) },
  filterCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  datesRow: { flexDirection: 'row', gap: spacing(2) },
  dateField: { flex: 1, minWidth: 0 },
  fieldLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '600',
    marginBottom: spacing(1),
  },
  dateInput: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    fontSize: 14,
  },
  chipRow: { flexDirection: 'row', gap: spacing(2), alignItems: 'center', paddingVertical: 2 },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    backgroundColor: colors.surfaceAlt,
  },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  actionRow: { flexDirection: 'row', marginTop: spacing(1) },
  btn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  btnFlex: { flex: 1 },
  btnDisabled: { opacity: 0.6 },
  btnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  error: { color: colors.destructive, fontSize: 12, marginTop: spacing(1) },
  hint: { color: colors.muted, marginBottom: spacing(2) },
  list: { gap: spacing(3) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    gap: spacing(1.5),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(1),
  },
  cardIndex: {
    color: colors.primaryForeground,
    backgroundColor: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: spacing(2),
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  cardTitle: { color: colors.foreground, fontSize: 15, fontWeight: '700', flex: 1, minWidth: 0 },
  viewImageBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1.5),
    flexShrink: 0,
  },
  viewImageBtnText: {
    color: colors.primaryForeground,
    fontSize: 11,
    fontWeight: '700',
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing(2),
    paddingVertical: 2,
  },
  cardLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', width: '38%' },
  cardValue: { color: colors.foreground, fontSize: 12, flex: 1, textAlign: 'right' },
  previewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'center',
    padding: spacing(4),
  },
  previewTouch: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  previewCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing(3),
    borderWidth: 1,
    borderColor: colors.border,
  },
  previewClose: { alignSelf: 'flex-end', marginBottom: spacing(2) },
  previewCloseText: { color: colors.foreground, fontSize: 18, fontWeight: '700' },
  previewImage: { width: '100%', height: 360 },
});
