/** Styles for BotDataScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  panel: {
    marginTop: spacing(3),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    gap: spacing(2),
  },
  rowTwo: { flexDirection: 'row', gap: spacing(2) },
  field: { flex: 1, gap: spacing(1) },
  label: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    fontSize: 14,
  },
  selectBtn: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  selectBtnText: { color: colors.foreground, fontSize: 13 },
  chipsWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2) },
  chip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginTop: spacing(2),
  },
  actionBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3.5),
    paddingVertical: spacing(2.5),
  },
  actionBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  totalUsers: { color: colors.foreground, fontSize: 13, marginTop: spacing(1) },
  bold: { fontWeight: '700' },
  muted: { color: colors.muted, fontSize: 13, marginTop: spacing(3) },
  cardsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(3),
    marginTop: spacing(3),
  },
  botCard: {
    width: '30%',
    minWidth: 100,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: 'rgba(255,159,10,0.35)',
    borderRadius: radius.md,
    padding: spacing(3),
  },
  botCardLabel: { color: colors.muted, fontSize: 11 },
  botCardId: { color: '#ffd28a', fontSize: 18, fontWeight: '700' },
  botCardCount: { color: colors.foreground, fontSize: 13, marginTop: spacing(1) },
  pickerSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: radius.md * 2,
    borderTopRightRadius: radius.md * 2,
    padding: spacing(4),
    maxHeight: '75%',
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  pickerChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    paddingVertical: spacing(3),
  },
  doneBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
    marginTop: spacing(1),
  },
  doneBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 14 },
});
