/** Styles for CallerDetailsScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  sub: {
    color: colors.muted,
    fontSize: 13,
    marginTop: spacing(1),
    marginBottom: spacing(3),
  },
  search: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    marginTop: spacing(3),
    marginBottom: spacing(3),
    fontSize: 14,
  },
  tabs: {
    flexDirection: 'row',
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  tab: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  tabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  tabTextActive: { color: colors.primaryForeground },
  error: { color: colors.destructive, fontSize: 13, marginBottom: spacing(3) },
  loader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(10),
    gap: spacing(2),
  },
  loaderText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  cardList: {
    marginTop: spacing(1),
    gap: spacing(2),
  },
  cardEmpty: {
    color: colors.muted,
    textAlign: 'center',
    paddingVertical: spacing(6),
    fontSize: 13,
  },
  cardHint: {
    color: colors.muted,
    fontSize: 11,
    textAlign: 'center',
    marginTop: spacing(1),
  },
  userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
    gap: spacing(3),
  },
  userCardSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(245, 179, 1, 0.08)',
  },
  dialerBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  selectAllBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surface,
  },
  selectAllText: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
  },
  addDialerBtn: {
    flex: 1,
    backgroundColor: '#ff9f0a',
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    alignItems: 'center',
  },
  addDialerBtnDisabled: {
    opacity: 0.5,
  },
  addDialerBtnText: {
    color: '#1a1200',
    fontSize: 12,
    fontWeight: '800',
  },
  checkBox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  checkBoxOn: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkBoxText: {
    color: colors.primaryForeground,
    fontSize: 12,
    fontWeight: '800',
  },
  callBtnRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(1.5),
  },
  callBtn: {
    backgroundColor: '#ff9f0a',
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2.5),
    paddingVertical: 5,
  },
  callBtnDisabled: {
    opacity: 0.5,
  },
  callBtnText: {
    color: '#1a1200',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(245, 179, 1, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(245, 179, 1, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: colors.primary,
    fontWeight: '800',
    fontSize: 16,
  },
  userCardMid: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userCardName: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 14,
  },
  userCardNameLink: {
    color: colors.foreground,
  },
  userCardSub: {
    color: colors.muted,
    fontSize: 12,
  },
  userCardTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing(1.5),
    marginTop: spacing(1),
  },
  tagApp: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: colors.border,
    maxWidth: '100%',
    flexShrink: 1,
  },
  tagState: {
    maxWidth: '72%',
  },
  tagAppText: {
    color: colors.foreground,
    fontSize: 10,
    fontWeight: '700',
    flexShrink: 1,
  },
  tagPlay: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderWidth: 1,
    flexShrink: 0,
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
  },
  tagPlayE: {
    backgroundColor: 'rgba(59, 130, 246, 0.12)',
    borderColor: 'rgba(59, 130, 246, 0.4)',
  },
  tagPlayC: {
    backgroundColor: 'rgba(168, 85, 247, 0.12)',
    borderColor: 'rgba(168, 85, 247, 0.4)',
  },
  tagPlayS: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderColor: 'rgba(34, 197, 94, 0.4)',
  },
  tagPlayText: {
    color: colors.foreground,
    fontSize: 10,
    fontWeight: '700',
  },
  tagStatus: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderWidth: 1,
    flexShrink: 0,
  },
  tagActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderColor: 'rgba(34, 197, 94, 0.4)',
  },
  tagWarning: {
    backgroundColor: 'rgba(245, 179, 1, 0.12)',
    borderColor: 'rgba(245, 179, 1, 0.4)',
  },
  tagInactive: {
    backgroundColor: 'rgba(148, 163, 184, 0.12)',
    borderColor: 'rgba(148, 163, 184, 0.4)',
  },
  tagStatusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  tagActiveText: {
    color: colors.success,
  },
  tagWarningText: {
    color: colors.primary,
  },
  tagInactiveText: {
    color: colors.muted,
  },
  userCardRight: {
    alignItems: 'flex-end',
    gap: 2,
    flexShrink: 0,
  },
  userCardBalance: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 13,
  },
  userCardIdx: {
    color: colors.muted,
    fontSize: 10,
  },
});
