/** Styles for CallerAllotmentScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing(2), paddingBottom: spacing(6), gap: spacing(1.5) },
  title: { color: colors.foreground, fontSize: 22, fontWeight: '800' },
  hint: { color: colors.muted, fontSize: 13, marginBottom: spacing(0.5) },
  error: { color: '#ef5350', fontSize: 13 },
  emptyHint: { color: colors.muted, marginTop: spacing(2) },
  list: { gap: spacing(2), marginTop: spacing(1) },
  cardBlocked: {
    opacity: 0.55,
  },
  statusPill: {
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  statusActive: {
    color: '#166534',
    backgroundColor: 'rgba(22,163,74,0.18)',
  },
  statusBlocked: {
    color: '#991b1b',
    backgroundColor: 'rgba(220,38,38,0.18)',
  },
  cardSplitRight: {
    color: colors.foreground,
    fontSize: 11,
    fontWeight: '700',
    flexShrink: 0,
    maxWidth: '55%',
    textAlign: 'right',
  },
  idBlock: {
    marginTop: spacing(1),
    paddingTop: spacing(1),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 2,
  },
  editBlock: { gap: spacing(1.5), marginBottom: spacing(2) },
  editTitle: { color: colors.foreground, fontWeight: '800', fontSize: 16 },
  editHint: { color: colors.muted, fontSize: 12, marginTop: -spacing(1) },
  menuGrid: { flexDirection: 'row', gap: spacing(1.5) },
  menuBtn: {
    flex: 1,
    minHeight: 72,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(0.5),
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    padding: spacing(1.5),
  },
  menuBtnActive: { borderColor: colors.primary, backgroundColor: 'rgba(245,179,1,0.12)' },
  menuIcon: { color: colors.primary, fontSize: 18, fontWeight: '800' },
  menuText: { color: colors.foreground, fontSize: 11, fontWeight: '700', textAlign: 'center' },
  menuTextActive: { color: colors.primary },
  editorCard: {
    gap: spacing(1.5),
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    padding: spacing(2.5),
  },
  editorTitle: { color: colors.foreground, fontSize: 15, fontWeight: '800' },
  currentText: { color: colors.muted, fontSize: 12 },
  fieldCaption: { color: colors.foreground, fontWeight: '700', fontSize: 12 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(1) },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(1.25),
    paddingVertical: spacing(0.75),
    backgroundColor: colors.surface,
  },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  chipTextActive: { color: '#fff' },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    color: colors.foreground,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
    fontSize: 13,
  },
  saveBtn: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    marginTop: spacing(0.5),
  },
  saveBtnText: { color: colors.primaryForeground, fontSize: 13, fontWeight: '800' },
  removeBtn: {
    minHeight: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.destructive,
  },
  removeBtnText: { color: colors.destructive, fontSize: 13, fontWeight: '800' },
  headActions: { flexDirection: 'row', gap: spacing(1.5) },
  flexBtn: { flex: 1 },
  btnDisabled: { opacity: 0.45 },
});
