/** Styles for CallLogsScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  sub: { color: colors.muted, fontSize: 12, marginTop: spacing(1), marginBottom: spacing(2) },
  sectionTitle: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    marginTop: spacing(4),
    marginBottom: spacing(2),
  },
  collapseHeader: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    marginTop: spacing(3),
  },
  collapseTitle: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  filterCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    gap: spacing(2.5),
    marginTop: spacing(2),
  },
  filterRow: { gap: spacing(1) },
  filterLabel: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  filterInput: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    fontSize: 14,
  },
  chipRow: { flexDirection: 'row', alignItems: 'center', gap: spacing(2) },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2) },
  chipRowSpaced: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginTop: spacing(3),
  },
  chipRowLabel: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  chip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  filterActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing(2),
    marginTop: spacing(1),
  },
  clearBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2.5),
  },
  clearBtnText: { color: colors.foreground, fontWeight: '600', fontSize: 13 },
  searchBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2.5),
    minWidth: 72,
    alignItems: 'center',
  },
  dialerHint: { color: colors.muted, fontSize: 11 },
  dialerMsg: { color: colors.foreground, fontSize: 12, textAlign: 'center' },
  dialerBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  cardCheck: {
    width: 28,
    height: 28,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
  },
  cardCheckOn: { borderColor: colors.primary, backgroundColor: 'rgba(37,99,235,0.12)' },
  cardCheckText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  cardCheckTextOn: { color: colors.primary },
  cardActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(1.5),
  },
  cardActionBtn: {
    backgroundColor: '#ff9f0a',
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2.5),
    paddingVertical: 5,
  },
  cardActionBtnDisabled: {
    opacity: 0.5,
  },
  cardActionBtnText: {
    color: '#1a1200',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  selectAllRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing(3),
    marginBottom: spacing(1),
  },
  selectAllBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    backgroundColor: colors.surface,
  },
  selectAllText: { color: colors.foreground, fontSize: 12, fontWeight: '700' },
  selectedCount: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  actionMsgBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginTop: spacing(3),
  },
  actionMsgText: { color: colors.foreground, fontSize: 13, flex: 1 },
  actionMsgClose: { color: colors.muted, fontSize: 14 },
  loadingBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(10),
    gap: spacing(2),
  },
  botGrid: { gap: spacing(3), marginTop: spacing(3) },
  botStatusBlock: { marginTop: spacing(3), marginBottom: spacing(2) },
  botStatusHeader: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  botStatusActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing(2),
    marginTop: spacing(3),
  },
  botStatusActionBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surface,
  },
  botStatusActionText: { color: colors.foreground, fontSize: 12, fontWeight: '700' },
  reinitBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  reinitBtnText: { color: colors.primaryForeground, fontSize: 12, fontWeight: '700' },
  botCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  botCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
  },
  botCardTitle: { color: colors.foreground, fontSize: 14, fontWeight: '700' },
  botCardState: { color: colors.muted, fontSize: 12, flexShrink: 1 },
  botChipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2.5),
    marginTop: spacing(3),
  },
  botChip: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1.5),
    alignItems: 'center',
    minWidth: 72,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  botChipReinit: { minWidth: 84 },
  botChipSelected: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(245,179,1,0.16)',
  },
  botChipValue: { color: colors.foreground, fontSize: 15, fontWeight: '700' },
  botChipLabel: { color: colors.muted, fontSize: 10, marginTop: 2, textAlign: 'center' },
  botChipReinitHint: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '700',
    marginTop: 4,
  },
  loadingText: { color: colors.muted, fontSize: 13 },
  pagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing(3),
    gap: spacing(2),
  },
  pagerBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surface,
  },
  pagerBtnDisabled: { opacity: 0.4 },
  pagerBtnText: { color: colors.foreground, fontSize: 13, fontWeight: '600' },
  pagerInfo: { color: colors.muted, fontSize: 12, flexShrink: 1, textAlign: 'center' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: spacing(4),
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(4),
    gap: spacing(3),
    maxHeight: '80%',
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  modalSub: { color: colors.muted, fontSize: 12 },
  modalChips: { maxHeight: 220 },
  summaryScroll: { maxHeight: 480 },
  summaryCard: {
    backgroundColor: '#fff',
    maxWidth: 720,
    width: '100%',
    alignSelf: 'center',
  },
  summaryModalTitle: {
    color: '#111',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: spacing(1.5),
  },
  summaryLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 180,
    gap: spacing(2),
  },
  summaryLoadingText: { color: '#555', fontSize: 13, fontWeight: '600' },
  summaryError: {
    color: colors.destructive,
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: spacing(6),
  },
  summaryTable: {
    borderWidth: 1,
    borderColor: '#9e9e9e',
    borderRadius: 4,
    overflow: 'hidden',
  },
  summaryTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#9e9e9e',
  },
  summaryTableHead: { backgroundColor: 'orange' },
  summaryRowEven: { backgroundColor: '#fff' },
  summaryRowOdd: { backgroundColor: '#f5f5f5' },
  summaryTh: {
    color: '#000',
    fontWeight: '800',
    fontSize: 12,
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(1.25),
  },
  summaryTdAttr: {
    color: '#000',
    fontWeight: '700',
    fontSize: 12,
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(1.25),
  },
  summaryTd: {
    color: '#000',
    fontSize: 12,
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(1.25),
  },
  summaryColAttr: { width: '28%' },
  summaryColValue: { width: '40%' },
  summaryColReason: { flex: 1 },
  summaryValue: { color: '#111', fontSize: 13 },
});
