/** Styles for CasinoTopupBalanceScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  mutedBox: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginTop: spacing(3),
  },
  mutedText: { color: colors.muted, fontSize: 13 },
  section: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    marginTop: spacing(3),
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing(2) },
  sectionTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  sectionSub: { color: colors.muted, fontSize: 12, marginTop: spacing(0.5) },
  actionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2), marginBottom: spacing(2) },
  actionBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
  },
  actionBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 12 },
  addBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3.5),
  },
  addBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing(1.5),
  },
  metricChip: {
    width: '32%',
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(1.5),
  },
  metricLabel: { color: colors.muted, fontSize: 9, fontWeight: '600' },
  metricValue: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '800',
    marginTop: spacing(0.5),
  },
  list: { gap: spacing(2), marginTop: spacing(2) },
  listHint: { color: colors.muted, marginTop: spacing(2), marginBottom: spacing(1), fontSize: 13 },
  tabLoader: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(8),
    gap: spacing(2),
  },
  card: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(2.5),
    gap: 2,
  },
  cardNote: { color: colors.muted, fontSize: 11, marginTop: spacing(0.5) },
  rangeText: { color: colors.muted, fontSize: 12, marginTop: spacing(2), marginBottom: spacing(1) },
  balanceBox: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
  },
  balanceLabel: { color: colors.muted, fontSize: 12 },
  balanceValue: {
    color: colors.foreground,
    fontSize: 24,
    fontWeight: '700',
    marginTop: spacing(1),
  },
  balanceCurrency: { color: colors.muted, fontSize: 14, fontWeight: '500' },
  inputMultiline: { minHeight: 64, textAlignVertical: 'top' },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    backgroundColor: colors.surface,
  },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
});
