/** Styles for DepositProvidersScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  searchRow: { flexDirection: 'row', alignItems: 'center', marginTop: spacing(3) },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    fontSize: 14,
  },
  headerBtns: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(3) },
  headerBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(4),
  },
  headerBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  headerBtnAlt: {
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(4),
  },
  headerBtnAltText: { color: colors.primary, fontWeight: '700', fontSize: 13 },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginTop: spacing(2),
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    backgroundColor: colors.surface,
  },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  removeChip: {
    borderColor: 'rgba(239,68,68,0.45)',
    backgroundColor: 'rgba(239,68,68,0.12)',
  },
  removeChipText: { color: '#ef5350', fontSize: 12, fontWeight: '700' },
  midRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
  },
  midEnableBtn: {
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.55)',
    borderRadius: radius.md,
    paddingVertical: spacing(1),
    paddingHorizontal: spacing(2.5),
  },
  midEnableBtnActive: {
    backgroundColor: 'rgba(34,197,94,0.2)',
    borderColor: '#22c55e',
  },
  midEnableText: { color: '#4ade80', fontSize: 11, fontWeight: '700' },
  midEnableTextActive: { color: '#166534' },
  midDeleteBtn: {
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.55)',
    borderRadius: radius.md,
    paddingVertical: spacing(1),
    paddingHorizontal: spacing(2.5),
  },
  midDeleteText: { color: '#ef5350', fontSize: 11, fontWeight: '700' },
  midName: { flex: 1, color: colors.foreground, fontSize: 12, fontWeight: '600' },
  statusPill: {
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  statusOn: { color: '#166534', backgroundColor: 'rgba(22,163,74,0.18)' },
  statusOff: { color: '#991b1b', backgroundColor: 'rgba(220,38,38,0.18)' },
  backdropCentered: { justifyContent: 'center', padding: spacing(4) },
  backdropTouchFill: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  modalSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: radius.md * 2,
    borderTopRightRadius: radius.md * 2,
    padding: spacing(4),
  },
  modalSheetRaised: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md * 2,
    maxHeight: '82%',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    fontSize: 14,
    marginTop: spacing(2.5),
  },
  submitText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 14 },
});
