/** Styles for EmpCodePieChartModal — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.72)',
    justifyContent: 'center',
    padding: spacing(3),
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: '94%',
    padding: spacing(4),
    gap: spacing(2),
  },
  header: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing(2),
  },
  headerText: { flex: 1, minWidth: 0 },
  title: { color: colors.foreground, fontSize: 18, fontWeight: '800' },
  subtitle: { color: colors.muted, fontSize: 12, marginTop: 2 },
  closeHit: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
  },
  close: { color: colors.muted, fontSize: 16, fontWeight: '700' },
  tabs: { flexDirection: 'row', gap: spacing(2) },
  tab: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(2),
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
  },
  tabActive: {
    borderColor: colors.primary,
    backgroundColor: `${colors.primary}22`,
  },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  tabTextActive: { color: colors.primary },
  loader: { alignItems: 'center', paddingVertical: spacing(8), gap: spacing(2) },
  hint: { color: colors.muted, fontSize: 12, textAlign: 'center', marginTop: spacing(2) },
  contentSplit: {
    minHeight: 280,
    maxHeight: 440,
  },
  chartStage: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(1),
    marginBottom: spacing(2),
    alignItems: 'center',
    overflow: 'hidden',
  },
  pieWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPie: {
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyPieText: { color: colors.muted, fontSize: 13 },
  legendTitle: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '800',
    marginBottom: spacing(1),
  },
  listScroll: {
    flexGrow: 0,
    maxHeight: 240,
  },
  listContent: {
    paddingBottom: spacing(2),
  },
  legendCard: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(2.5),
    marginBottom: spacing(2),
    gap: spacing(1),
  },
  legendTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
  },
  swatch: { width: 12, height: 12, borderRadius: 4 },
  legendName: { flex: 1, color: colors.foreground, fontSize: 13, fontWeight: '700' },
  legendCount: { color: colors.foreground, fontSize: 14, fontWeight: '800' },
  barTrack: {
    height: 6,
    borderRadius: 99,
    backgroundColor: colors.border,
    overflow: 'hidden',
  },
  barFill: { height: 6, borderRadius: 99 },
  legendPct: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  closeBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  closeBtnText: { color: '#fff', fontWeight: '800', fontSize: 14 },
});
