/** Styles for IncomingBotCallScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  title: { color: colors.foreground, fontSize: 20, fontWeight: '700', marginBottom: spacing(1) },
  sub: { color: colors.muted, fontSize: 12, marginBottom: spacing(3) },
  filterWrap: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  dateRow: { flexDirection: 'row', gap: spacing(2) },
  dateField: { flex: 1 },
  field: { gap: spacing(1) },
  fieldLabel: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    fontSize: 14,
  },
  searchGrid: { flexDirection: 'row', gap: spacing(2) },
  searchCell: { flex: 1 },
  filterActions: { flexDirection: 'row', gap: spacing(2) },
  filterActionBtn: { flex: 1 },
  applyBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  syncBtn: {
    backgroundColor: '#1976d2',
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  syncText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(3),
  },
  hint: { color: colors.muted, fontSize: 13, marginBottom: spacing(2) },
  list: { gap: spacing(2) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
  },
  cardNoComment: {
    backgroundColor: 'rgba(255,159,10,0.08)',
    borderColor: 'rgba(255,159,10,0.28)',
  },
  cardHasComment: {
    backgroundColor: 'rgba(34,197,94,0.08)',
    borderColor: 'rgba(34,197,94,0.28)',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(1.5),
  },
  cardIndex: { color: colors.muted, fontSize: 11, fontWeight: '700', minWidth: 28 },
  cardTitle: { color: colors.foreground, fontSize: 14, fontWeight: '700', flex: 1, minWidth: 0 },
  statusPill: {
    fontSize: 10,
    fontWeight: '700',
    paddingHorizontal: spacing(2),
    paddingVertical: 3,
    borderRadius: 999,
    overflow: 'hidden',
    maxWidth: 110,
    textAlign: 'center',
  },
  cardSplitRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing(2),
    marginBottom: spacing(0.5),
  },
  cardSplitLeft: { color: colors.muted, fontSize: 12, flex: 1, minWidth: 0 },
  cardSplitRight: { color: colors.muted, fontSize: 12, flexShrink: 0, maxWidth: '48%' },
  cardActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(2),
  },
  callBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  callBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 12 },
  commentBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  commentBtnText: { color: colors.foreground, fontWeight: '600', fontSize: 12 },
  btnDisabled: { opacity: 0.55 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    padding: spacing(5),
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing(4),
    gap: spacing(3),
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  commentInput: {
    minHeight: 96,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    color: colors.foreground,
    backgroundColor: colors.surfaceAlt,
    fontSize: 14,
  },
  modalActions: { flexDirection: 'row', gap: spacing(2) },
  modalBtnOutline: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  modalBtnOutlineText: { color: colors.foreground, fontWeight: '600' },
  modalBtnPrimary: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  modalBtnPrimaryText: { color: colors.primaryForeground, fontWeight: '700' },
  backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  summarySheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(4),
    maxHeight: '80%',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing(3),
  },
  summaryTitle: { color: colors.foreground, fontSize: 17, fontWeight: '700', flex: 1, paddingRight: 8 },
  close: { color: colors.muted, fontSize: 18, fontWeight: '700' },
  summaryCard: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
    gap: spacing(1),
  },
  summaryAttr: { color: colors.primary, fontSize: 13, fontWeight: '700' },
  summaryValue: { color: colors.foreground, fontSize: 14 },
  summaryReason: { color: colors.muted, fontSize: 12 },
  summaryEmpty: { color: colors.muted, textAlign: 'center', marginVertical: spacing(6) },
  summaryError: {
    color: colors.destructive,
    textAlign: 'center',
    marginVertical: spacing(6),
    fontSize: 14,
    paddingHorizontal: spacing(2),
  },
  screen: { flex: 1 },
});
