/** Styles for LiveMatchTotalScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  page: { flex: 1 },
  viewBookBar: {
    paddingHorizontal: spacing(4),
    paddingTop: spacing(2),
    paddingBottom: spacing(3),
  },
  viewBookBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
  },
  viewBookText: {
    color: colors.primaryForeground,
    fontWeight: '800',
    fontSize: 15,
  },
  bookLoader: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  collapseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    marginBottom: spacing(2),
  },
  collapseTitle: { color: colors.foreground, fontWeight: '700', fontSize: 14 },
  collapseChevron: { color: colors.muted, fontSize: 12 },
  bookTypeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginTop: spacing(2),
    marginBottom: spacing(1),
  },
  bookTypeBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  bookTypeBtnActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  bookTypeText: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 13,
  },
  bookTypeTextActive: {
    color: colors.primaryForeground,
  },
  bookTypeHint: {
    color: colors.muted,
    fontSize: 12,
  },
  switcherBox: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    marginTop: spacing(3),
    marginBottom: spacing(3),
    paddingVertical: spacing(2),
  },
  switcherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing(3),
    marginBottom: spacing(2),
  },
  backBtn: { paddingVertical: spacing(0.5) },
  backText: { color: colors.primary, fontSize: 13, fontWeight: '800' },
  matchCount: {
    color: colors.primary,
    backgroundColor: 'rgba(255,159,10,0.14)',
    borderRadius: radius.sm,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(0.5),
  },
  switcherContent: { paddingHorizontal: spacing(3), gap: spacing(1.5) },
  switcherChip: {
    maxWidth: 190,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1.5),
  },
  switcherChipActive: {
    borderColor: colors.primary,
    backgroundColor: 'rgba(255,159,10,0.16)',
  },
  switcherChipText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  switcherChipTextActive: { color: colors.primary },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    marginBottom: spacing(2),
  },
  listRowMain: { flex: 1 },
  listRowName: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  listRowMeta: {
    color: colors.muted,
    fontSize: 11,
    marginTop: spacing(0.5),
  },
  listChevron: { color: colors.muted, fontSize: 20, fontWeight: '700' },
  liveDot: {
    color: colors.destructive,
    fontSize: 9,
    fontWeight: '800',
  },
  loading: { paddingVertical: spacing(8), alignItems: 'center' },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(3),
  },
  emptyBox: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    padding: spacing(4),
  },
  emptyText: { color: colors.muted, fontSize: 13 },
  sportBlock: { marginBottom: spacing(4) },
  sportHeader: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '700',
    backgroundColor: colors.surfaceAlt,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    borderRadius: radius.sm,
    marginBottom: spacing(2),
  },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3.5),
    marginBottom: spacing(3),
  },
  matchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    marginBottom: spacing(3),
    paddingHorizontal: spacing(2),
  },
  matchName: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
    paddingVertical: spacing(2),
    flex: 1,
  },
  liveTvBtn: {
    paddingHorizontal: spacing(1.5),
    paddingVertical: spacing(1),
  },
  liveTvText: { color: colors.destructive, fontSize: 12, fontWeight: '800' },
  oddsWrap: { flexDirection: 'row', gap: spacing(1), marginBottom: spacing(3) },
  oddsGroup: { flex: 1 },
  oddsLabel: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: spacing(1),
  },
  oddsCells: { flexDirection: 'row', gap: spacing(0.5) },
  oddsCell: {
    flex: 1,
    borderRadius: radius.sm,
    paddingVertical: spacing(1),
    alignItems: 'center',
  },
  backCell: { backgroundColor: '#1d4665' },
  layCell: { backgroundColor: '#90101a' },
  oddsPrice: { color: '#fff', fontSize: 11, fontWeight: '700' },
  oddsSize: { color: '#fff', fontSize: 9 },
  section: { marginBottom: spacing(3) },
  sectionTitle: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: spacing(1.5),
  },
  plRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: spacing(1),
  },
  plLabel: { color: colors.muted, fontSize: 13, flexShrink: 1 },
  plValue: { color: colors.success, fontSize: 13, fontWeight: '700' },
  negative: { color: colors.destructive },
  fancyBlock: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    padding: spacing(2),
    marginBottom: spacing(2),
  },
  fancyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  fancyTitle: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
    marginRight: spacing(2),
  },
  chevron: { color: colors.muted, fontSize: 12 },
  fancyRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: spacing(0.75),
    paddingHorizontal: spacing(1.5),
    borderRadius: radius.sm,
    marginTop: spacing(0.5),
  },
  fancyRowActive: { backgroundColor: 'rgba(255,192,203,0.18)' },
  fancyKey: { color: colors.foreground, fontSize: 13 },
  fancyKeyActive: { fontWeight: '700' },
  fancyVal: { color: colors.success, fontSize: 13, fontWeight: '600' },
  showMore: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: spacing(1),
  },
});
