/** Styles for LudoPlayerWiseRtpScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  screen: { flex: 1, backgroundColor: colors.background },
  title: { color: colors.foreground, fontSize: 20, fontWeight: '800', marginBottom: spacing(1) },
  sub: { color: colors.muted, fontSize: 13, marginBottom: spacing(3) },
  filterLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    marginTop: spacing(2),
    marginBottom: spacing(1.5),
  },
  chips: { flexDirection: 'row', gap: spacing(2), paddingBottom: spacing(1) },
  chip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  chipActive: { borderColor: colors.primary, backgroundColor: 'rgba(255,159,10,0.15)' },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  chipTextActive: { color: colors.foreground },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    fontSize: 14,
    marginBottom: spacing(2),
  },
  actionsRow: { flexDirection: 'row', gap: spacing(2), marginVertical: spacing(2) },
  actionBtn: {
    flex: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  actionBtnPrimary: { backgroundColor: colors.primary },
  actionBtnPrimaryText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  actionBtnAccent: {
    backgroundColor: '#ff9f0a',
  },
  actionBtnAccentText: { color: '#1a1200', fontWeight: '700', fontSize: 13 },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(3),
  },
  boundsBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    marginBottom: spacing(3),
    backgroundColor: colors.surface,
  },
  boundsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  boundsTitle: { color: colors.foreground, fontWeight: '700', fontSize: 14 },
  boundsToggle: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  boundCard: {
    marginTop: spacing(2),
    padding: spacing(2.5),
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255,159,10,0.25)',
    backgroundColor: 'rgba(255,159,10,0.06)',
  },
  boundGame: { color: colors.foreground, fontWeight: '700', fontSize: 12, marginBottom: spacing(1) },
  boundRow: { flexDirection: 'row', justifyContent: 'space-between' },
  boundMin: { color: '#66bb6a', fontWeight: '700', fontSize: 12 },
  boundMax: { color: '#ef5350', fontWeight: '700', fontSize: 12 },
  empty: { color: colors.muted, textAlign: 'center', marginTop: spacing(6) },
  list: { gap: spacing(2), marginTop: spacing(2) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(1),
  },
  cardIndex: { color: colors.muted, fontSize: 11, fontWeight: '700', minWidth: 22 },
  cardTitle: { color: colors.foreground, fontSize: 14, fontWeight: '700', flex: 1, minWidth: 0 },
  editChip: {
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1),
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  editChipText: { color: colors.foreground, fontSize: 11, fontWeight: '700' },
  cardMeta: { color: colors.muted, fontSize: 12, marginTop: 2 },
  backdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  formSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    padding: spacing(4),
    paddingBottom: spacing(8),
  },
  formTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '800',
    marginBottom: spacing(2),
  },
  formActions: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(4) },
  formBtnGhost: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
  btnDisabled: { opacity: 0.55 },
});
