/** Styles for MidLimitsScreen — shared presets from styles/common plus screen-specific keys. */
import { StyleSheet } from 'react-native';
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  content: { padding: spacing(4), paddingBottom: spacing(12) },
  overline: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  title: { color: colors.foreground, fontSize: 24, fontWeight: '800', marginTop: spacing(1) },
  subtitle: { color: colors.muted, fontSize: 13, marginTop: spacing(1), lineHeight: 18 },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginTop: spacing(4),
  },
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    paddingHorizontal: spacing(3),
    minHeight: 44,
  },
  searchInput: {
    flex: 1,
    color: colors.foreground,
    fontSize: 14,
    paddingVertical: spacing(2),
  },
  alertBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1),
    backgroundColor: '#ff9f0a',
    borderRadius: radius.md,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
  },
  alertBtnText: { color: '#1a1200', fontWeight: '700', fontSize: 13 },
  alertInfoBox: {
    marginTop: spacing(3),
    backgroundColor: 'rgba(255,159,10,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,159,10,0.25)',
    borderRadius: radius.lg,
    padding: spacing(3),
  },
  alertInfoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    flexWrap: 'wrap',
  },
  alertInfoTitle: { color: colors.foreground, fontWeight: '800', fontSize: 13 },
  alertStatusChip: {
    backgroundColor: 'rgba(255,159,10,0.18)',
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: 2,
  },
  alertStatusChipOff: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  alertStatusChipText: { color: '#ff9f0a', fontSize: 11, fontWeight: '700' },
  alertStatusChipTextOff: { color: colors.muted },
  alertRecipientList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(2),
  },
  alertRecipientChip: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1),
    maxWidth: '100%',
  },
  alertRecipientChipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  alertInfoEmpty: { color: colors.muted, fontSize: 12, marginTop: spacing(2), lineHeight: 17 },
  statsRow: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(3) },
  statChip: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(3),
  },
  statValue: { color: colors.foreground, fontSize: 20, fontWeight: '800' },
  statLabel: { color: colors.muted, fontSize: 11, marginTop: 2 },
  loadingWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(8),
    gap: spacing(2),
  },
  loadingText: { color: colors.muted, fontSize: 13 },
  list: { gap: spacing(2.5), marginTop: spacing(3) },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3.5),
  },
  cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing(2) },
  cardMain: { flex: 1, minWidth: 0 },
  cardMid: { color: colors.foreground, fontSize: 16, fontWeight: '800' },
  cardGateway: { color: colors.muted, fontSize: 12, marginTop: 2 },
  indexBadge: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: radius.sm,
    minWidth: 28,
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: spacing(1.5),
  },
  indexBadgeText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  cardBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing(3),
  },
  limitBlock: { flex: 1 },
  limitLabel: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  limitValue: { color: colors.primary, fontSize: 18, fontWeight: '800', marginTop: 2 },
  limitUnset: { color: colors.muted, fontSize: 14, fontWeight: '600' },
  editBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(2.5),
  },
  editBtnText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  cardMeta: { color: colors.muted, fontSize: 11, marginTop: spacing(2) },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing(10),
    gap: spacing(2),
  },
  emptyTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  emptyText: { color: colors.muted, fontSize: 13, textAlign: 'center' },
  deniedWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing(6),
    gap: spacing(2),
  },
  deniedTitle: { color: colors.foreground, fontSize: 18, fontWeight: '700' },
  deniedText: { color: colors.muted, fontSize: 13, textAlign: 'center' },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  modalBackdrop: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  modalSheet: {
    backgroundColor: colors.background,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    paddingHorizontal: spacing(4),
    paddingBottom: spacing(6),
    paddingTop: spacing(2),
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  recipientsSheet: { maxHeight: '88%' },
  modalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: spacing(3),
  },
  modalTitle: { color: colors.foreground, fontSize: 18, fontWeight: '800' },
  modalHint: { color: colors.muted, fontSize: 12, marginTop: spacing(1.5), lineHeight: 17 },
  fieldLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', marginTop: spacing(4) },
  fieldInput: {
    marginTop: spacing(1.5),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    fontSize: 16,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing(2),
    marginTop: spacing(4),
  },
  cancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  cancelBtnText: { color: colors.foreground, fontWeight: '700' },
  saveBtn: {
    flex: 1,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    alignItems: 'center',
  },
  saveBtnText: { color: colors.primaryForeground, fontWeight: '700' },
  btnDisabled: { opacity: 0.6 },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing(4),
    paddingVertical: spacing(1),
  },
  switchLabel: { color: colors.foreground, fontWeight: '600', fontSize: 14 },
  chatIdsLabel: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 13,
    marginTop: spacing(2),
  },
  chatIdsInput: {
    marginTop: spacing(1),
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    backgroundColor: colors.background,
    color: colors.foreground,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(2),
    fontSize: 14,
    minHeight: 72,
    textAlignVertical: 'top',
  },
  chatIdsHint: {
    color: colors.muted,
    fontSize: 11,
    marginTop: spacing(1),
    marginBottom: spacing(1),
  },
  recipientCount: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 13,
    marginTop: spacing(3),
    marginBottom: spacing(1.5),
  },
  recipientList: {
    maxHeight: 280,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
  },
  recipientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2.5),
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  recipientInfo: { flex: 1, minWidth: 0 },
  recipientName: { color: colors.foreground, fontWeight: '700', fontSize: 14 },
  recipientMeta: { color: colors.muted, fontSize: 11, marginTop: 2 },
});
