/** Styles for NandiPlatformScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  sub: { color: colors.muted, fontSize: 13, marginTop: spacing(1), marginBottom: spacing(3) },
  error: { color: colors.destructive, fontSize: 13, marginBottom: spacing(3) },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  sectionTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginBottom: spacing(4),
  },
  summaryCard: {
    width: '48%',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  summaryLabel: { color: colors.muted, fontSize: 11 },
  summaryValue: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    marginTop: spacing(1),
  },
  empty: { color: colors.muted, fontSize: 13, marginBottom: spacing(3) },
  tabsScroll: { marginBottom: spacing(3) },
  tabs: { flexDirection: 'row', gap: spacing(2) },
  tab: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surface,
  },
  tabActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  tabText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  tabTextActive: { color: '#fff' },
  bazarList: { gap: spacing(3), marginBottom: spacing(4) },
  dimmed: { opacity: 0.55 },
  bazarCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(3),
    backgroundColor: colors.surface,
  },
  bazarCardSelected: { borderColor: colors.primary },
  bazarHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  bazarHeadMain: { flex: 1, minWidth: 0 },
  bazarName: { color: colors.foreground, fontSize: 15, fontWeight: '700' },
  bazarTimes: { color: colors.muted, fontSize: 11, marginTop: 2 },
  result: {
    color: colors.foreground,
    fontSize: 11,
    fontWeight: '700',
    maxWidth: '42%',
    textAlign: 'right',
  },
  resultEmpty: { color: colors.muted },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2), marginBottom: spacing(2) },
  metricCell: { width: '30%' },
  metricK: { color: colors.muted, fontSize: 10 },
  metricV: { color: colors.foreground, fontSize: 13, fontWeight: '700', marginTop: 2 },
  session: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(2),
    marginTop: spacing(2),
    backgroundColor: colors.background,
  },
  sessionActive: { borderColor: colors.primary, backgroundColor: colors.surface },
  sessionLabel: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: spacing(1),
  },
  sessionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(1) },
  sessionCell: { width: '23%' },
  sessionV: { color: colors.foreground, fontSize: 11, fontWeight: '700' },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.45)' },
  modalTouch: { flex: 1 },
  modalSheet: {
    maxHeight: '85%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    paddingHorizontal: spacing(4),
    paddingBottom: spacing(4),
  },
  modalHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginVertical: spacing(2),
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  modalMeta: { color: colors.muted, fontSize: 12, marginTop: 2 },
  modalClose: { color: colors.muted, fontSize: 18, paddingHorizontal: 4 },
  playersBody: { gap: spacing(2), paddingBottom: spacing(6) },
  pageSizeRow: { flexDirection: 'row', gap: spacing(2), marginBottom: spacing(2) },
  pageChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1),
  },
  pageChipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  pageChipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  pageChipTextActive: { color: '#fff' },
  playerCard: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    backgroundColor: colors.background,
  },
  playerTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing(2) },
  playerName: { flex: 1, color: colors.foreground, fontWeight: '700', fontSize: 14 },
  playerGgr: { fontWeight: '700', fontSize: 14 },
  playerMeta: { color: colors.muted, fontSize: 12, marginTop: spacing(1) },
  playerLink: { color: colors.primary, fontSize: 12, marginTop: spacing(1), fontWeight: '600' },
  pager: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(3),
    marginTop: spacing(2),
  },
  pagerBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  pagerDisabled: { opacity: 0.4 },
  pagerText: { color: colors.foreground, fontWeight: '600' },
  pagerMeta: { color: colors.muted, fontSize: 13 },
});
