/** Styles for NonPerformingUserScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  list: { gap: spacing(3), marginTop: spacing(3) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    gap: spacing(1),
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(1.5),
  },
  cardIndex: {
    color: colors.primaryForeground,
    backgroundColor: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: spacing(2),
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  cardTitle: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
    minWidth: 0,
  },
  viewCommentBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1.5),
    flexShrink: 0,
  },
  viewCommentBtnText: {
    color: colors.primaryForeground,
    fontSize: 11,
    fontWeight: '700',
  },
  cardRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing(2),
    paddingVertical: 2,
  },
  cardLabel: { color: colors.muted, fontSize: 12, fontWeight: '600', width: '40%' },
  cardValue: { color: colors.foreground, fontSize: 12, flex: 1, textAlign: 'right' },
  cardHint: { color: colors.muted, fontSize: 11, marginTop: spacing(1.5) },
  backdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(10),
    backgroundColor: 'rgba(0,0,0,0.6)',
  },
  backdropTouch: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  sheet: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md * 2,
    padding: spacing(4),
    maxHeight: '100%',
  },
  sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  sheetTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
    marginRight: spacing(2),
  },
  sheetClose: { color: colors.muted, fontSize: 18, fontWeight: '700' },
  commentInputRow: { flexDirection: 'row', alignItems: 'flex-end', marginTop: spacing(3) },
  commentInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    fontSize: 14,
    marginRight: spacing(2),
    maxHeight: 100,
  },
  commentBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(4),
  },
  commentBtnDisabled: { opacity: 0.5 },
  commentBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  commentMsg: { color: colors.muted, fontSize: 12, marginTop: spacing(2) },
  commentList: { marginTop: spacing(3) },
  commentEmpty: {
    color: colors.muted,
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: spacing(4),
  },
  commentCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
  },
  commentText: { color: colors.foreground, fontSize: 14 },
  commentMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing(2),
  },
  commentMetaText: { color: colors.muted, fontSize: 11 },
});
