/** Styles for RolesResponsibilitiesScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  noPerm: { flex: 1, backgroundColor: 'transparent', padding: spacing(4) },
  noPermText: { color: colors.muted, fontSize: 14 },
  headerRow: { marginBottom: spacing(3) },
  backLink: { color: colors.primary, fontSize: 14, fontWeight: '600', marginBottom: spacing(2) },
  subCount: { color: colors.muted, fontSize: 12, marginTop: spacing(1) },
  respItem: { paddingVertical: spacing(1.5) },
  respItemText: { color: colors.foreground, fontSize: 13 },
  formBtnDanger: { backgroundColor: colors.destructive },
  actionsRow: { flexDirection: 'row', gap: spacing(2), marginBottom: spacing(3), flexWrap: 'wrap' },
  headBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2.5),
  },
  headBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(3),
  },
  roleCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
  },
  roleCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  roleCardName: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    flex: 1,
    marginRight: spacing(2),
  },
  roleCountPill: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(0.75),
  },
  roleCountText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  roleCardSub: { color: colors.muted, fontSize: 12, marginTop: spacing(1.5) },
  roleCardHint: { color: colors.muted, fontSize: 10, marginTop: spacing(1.5), fontStyle: 'italic' },
  formSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(4),
    gap: spacing(1),
  },
  editSheet: { maxHeight: '85%' },
  formTitle: {
    color: colors.foreground,
    fontSize: 17,
    fontWeight: '700',
    marginBottom: spacing(2),
  },
  fieldLabel: { color: colors.muted, fontSize: 11, fontWeight: '600', marginTop: spacing(2) },
  sectionLabel: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '700',
    marginTop: spacing(3),
    marginBottom: spacing(1),
  },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    fontSize: 14,
    marginTop: spacing(1),
  },
  chipsRow: { flexDirection: 'row', gap: spacing(2), paddingVertical: spacing(1) },
  chip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  chipText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  respScroll: { maxHeight: 320, marginTop: spacing(1) },
  groupBlock: { marginBottom: spacing(2) },
  groupLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', marginBottom: spacing(1) },
  checkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    paddingVertical: spacing(1.5),
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxOn: { backgroundColor: colors.primary, borderColor: colors.primary },
  checkboxTick: { color: colors.primaryForeground, fontSize: 13, fontWeight: '700' },
  checkLabel: { color: colors.foreground, fontSize: 13, flex: 1 },
  formActions: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(4) },
  formBtnGhost: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
});
