/** Styles for RowDetailSheet — shared presets from styles/common plus screen-specific keys. */
import { StyleSheet } from 'react-native';
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'flex-end' },
  sheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: '80%',
    paddingHorizontal: spacing(4),
    paddingTop: spacing(2),
  },
  handle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginBottom: spacing(2),
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: spacing(2),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  title: { color: colors.foreground, fontSize: 16, fontWeight: '700', flex: 1 },
  close: { color: colors.muted, fontSize: 18, paddingHorizontal: spacing(2) },
  scroll: { marginTop: spacing(1) },
  image: {
    width: '100%',
    height: 150,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    marginTop: spacing(2),
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    paddingVertical: spacing(2.5),
  },
  actionBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3.5),
    paddingVertical: spacing(2),
    backgroundColor: colors.surfaceAlt,
  },
  actionBtnPrimary: { backgroundColor: colors.primary, borderColor: colors.primary },
  actionBtnWarning: { backgroundColor: '#facc15', borderColor: '#facc15' },
  actionBtnDanger: { backgroundColor: '#ef5350', borderColor: '#ef5350' },
  actionBtnDisabled: { opacity: 0.5 },
  actionBtnText: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  actionBtnTextPrimary: { color: colors.primaryForeground },
  actionBtnTextWarning: { color: '#111' },
  actionBtnTextDanger: { color: '#fff' },
  note: {
    color: colors.muted,
    fontSize: 11,
    paddingBottom: spacing(2),
  },
  fieldBlock: {
    paddingVertical: spacing(2),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  fieldLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
  },
  blockValue: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '600',
    marginTop: spacing(1),
    lineHeight: 19,
  },
  fieldRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing(3),
    paddingVertical: spacing(2),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  label: { color: colors.muted, fontSize: 13, flexShrink: 0, maxWidth: '40%', paddingTop: 1 },
  valueSide: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    gap: spacing(1.5),
    minWidth: 0,
  },
  value: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
    flexShrink: 1,
    textAlign: 'right',
    lineHeight: 18,
  },
  copyBtn: {
    padding: spacing(0.5),
  },
  valueBadge: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1),
  },
  valueBadgeText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  singleActionBtn: {
    marginTop: spacing(4),
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
  },
  singleActionText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 14 },
});
