/** Styles for WhatsappMidScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  screen: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing(4), paddingBottom: spacing(8) },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing(4),
    gap: spacing(2),
  },
  headerText: { flex: 1, minWidth: 0 },
  title: { fontSize: 20, fontWeight: '800', color: colors.foreground },
  subtitle: { color: colors.muted, fontSize: 12, marginTop: 2 },
  addBtn: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2),
    borderRadius: radius.sm,
  },
  addBtnText: { color: colors.primaryForeground, fontWeight: '700' },
  errorBox: {
    backgroundColor: 'rgba(239,68,68,0.12)',
    padding: spacing(2),
    borderRadius: radius.sm,
    marginBottom: spacing(2),
  },
  errorText: { color: colors.destructive },
  hint: { color: colors.muted, marginBottom: spacing(2) },
  list: { gap: spacing(5) },
  group: { gap: spacing(1.5) },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(3),
    gap: spacing(2.5),
  },
  groupAccent: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 2,
    backgroundColor: colors.primary,
  },
  groupHeaderText: { flex: 1, minWidth: 0 },
  groupLabel: {
    color: colors.primary,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 2,
  },
  groupTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '800',
  },
  groupBadge: {
    minWidth: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing(2),
  },
  groupCount: {
    color: colors.primaryForeground,
    fontSize: 13,
    fontWeight: '800',
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(2.5),
  },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  cardName: {
    fontWeight: '700',
    color: colors.foreground,
    flex: 1,
    marginRight: 8,
    fontSize: 13,
  },
  cardSwitch: { transform: [{ scaleX: 0.85 }, { scaleY: 0.85 }] },
  cardMeta: { color: colors.muted, fontSize: 11, marginTop: 1, lineHeight: 14 },
  backdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  formSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    maxHeight: '85%',
  },
  formContent: {
    paddingHorizontal: spacing(4),
    paddingTop: spacing(4),
    gap: spacing(2),
  },
  formTitle: { fontSize: 18, fontWeight: '700', color: colors.foreground, marginBottom: 4 },
  fieldLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.4,
    marginBottom: -4,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    padding: spacing(2),
    color: colors.foreground,
    backgroundColor: colors.background,
  },
  chipRow: { maxHeight: 40 },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    backgroundColor: colors.surfaceAlt,
  },
  chipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  chipText: { color: colors.foreground, fontSize: 12 },
  chipTextActive: { color: colors.primaryForeground, fontWeight: '700' },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing(2),
    marginTop: spacing(2),
  },
  cancelBtn: {
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2),
  },
  cancelText: { color: colors.muted, fontWeight: '600' },
});
