/** Styles for WhatsappScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../../styles/common';
import { colors, isDarkTheme, radius, spacing } from '../../../theme';

export const styles = makeStyles({
  screen: { flex: 1, backgroundColor: colors.background },
  listHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing(4),
    paddingTop: spacing(4),
  },
  title: { color: colors.foreground, fontSize: 20, fontWeight: '800' },
  sub: { color: colors.muted, fontSize: 12, marginTop: spacing(0.5) },
  refreshBtn: {
    minWidth: 76,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  refreshText: { color: colors.primaryForeground, fontSize: 12, fontWeight: '700' },
  searchInput: {
    marginHorizontal: spacing(4),
    marginTop: spacing(3),
    marginBottom: spacing(2),
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    fontSize: 14,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  errorBox: {
    marginHorizontal: spacing(4),
    marginBottom: spacing(2),
    backgroundColor: 'rgba(239,68,68,0.12)',
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  chatList: { padding: spacing(4), paddingTop: spacing(1), gap: spacing(2) },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: spacing(8),
  },
  chatCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(3),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#2a4a3a',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  avatarText: { color: '#daf7f3', fontSize: 13, fontWeight: '800' },
  chatBody: { flex: 1, minWidth: 0 },
  chatTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
  },
  chatName: { color: colors.foreground, fontSize: 14, fontWeight: '700', flex: 1 },
  chatTime: { color: colors.muted, fontSize: 10, flexShrink: 0 },
  chatPhone: { color: colors.primary, fontSize: 11, marginTop: 1 },
  chatPreview: { color: colors.muted, fontSize: 12, marginTop: spacing(0.5) },
  conversationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2.5),
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  backBtn: {
    width: 30,
    height: 38,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backText: { color: colors.foreground, fontSize: 30, lineHeight: 32 },
  conversationTitle: { flex: 1, minWidth: 0 },
  activePhone: { color: colors.primary, fontSize: 11, marginTop: 1 },
  messagesWrap: { flex: 1 },
  messages: { flex: 1, backgroundColor: colors.background },
  messagesContent: { padding: spacing(3), gap: spacing(2), flexGrow: 1 },
  loadOlderWrap: {
    position: 'absolute',
    top: spacing(2),
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  loadOlderBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  loadOlderText: { color: colors.foreground, fontSize: 12, fontWeight: '700' },
  messageRow: { flexDirection: 'row' },
  messageRowIncoming: { justifyContent: 'flex-start' },
  messageRowOutgoing: { justifyContent: 'flex-end' },
  bubble: {
    maxWidth: '82%',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  bubbleIncoming: { backgroundColor: isDarkTheme() ? '#1f3d32' : '#d8f3e4' },
  bubbleOutgoing: { backgroundColor: isDarkTheme() ? colors.surfaceAlt : colors.surface },
  messageText: { color: colors.foreground, fontSize: 14, lineHeight: 20 },
  messageTime: {
    color: colors.muted,
    fontSize: 9,
    textAlign: 'right',
    marginTop: spacing(1),
  },
  messageImage: {
    width: 220,
    maxWidth: '100%',
    height: 180,
    borderRadius: radius.md,
    marginBottom: spacing(1),
    backgroundColor: colors.surface,
  },
  previewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    paddingHorizontal: spacing(3),
    paddingTop: spacing(2),
    backgroundColor: colors.surface,
  },
  previewImage: { width: 48, height: 48, borderRadius: radius.sm },
  removeImage: { color: colors.destructive, fontSize: 12, fontWeight: '700' },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: spacing(2),
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  attachBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceAlt,
  },
  attachText: { color: colors.foreground, fontSize: 24, lineHeight: 26 },
  messageInput: {
    flex: 1,
    maxHeight: 100,
    minHeight: 40,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    backgroundColor: colors.surfaceAlt,
    color: colors.foreground,
    fontSize: 14,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    textAlignVertical: 'top',
  },
  sendBtn: {
    minWidth: 58,
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
  },
  sendBtnDisabled: { opacity: 0.45 },
  sendText: { color: colors.primaryForeground, fontSize: 12, fontWeight: '800' },
});
