/** Styles for AdminLlmChatWidget — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../styles/common';
import { Platform } from 'react-native';
import { radius, spacing } from '../theme';

/** LLM chat chrome — always light panel (readable tables), independent of app theme. */
export const LLM = {
  bg: '#f8fafc',
  surface: '#ffffff',
  ink: '#0f172a',
  muted: '#64748b',
  border: '#cbd5e1',
  header: '#0f172a',
  headerInk: '#f8fafc',
  micBg: '#f5b301',
  micInk: '#1a1200',
  micRecordingBg: '#fee2e2',
  micRecordingInk: '#dc2626',
  sendBg: '#0f172a',
  sendInk: '#f8fafc',
  inputBg: '#ffffff',
  inputBorder: '#94a3b8',
};

export const styles = makeStyles({
  headerIconBtn: {
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
  },
  modalRoot: {
    flex: 1,
    backgroundColor: LLM.header,
  },
  keyboardRoot: {
    flex: 1,
    backgroundColor: LLM.bg,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: LLM.header,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  headerTitle: {
    color: LLM.headerInk,
    fontSize: 15,
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerActionBtn: {
    padding: spacing(1.5),
  },
  messagesFlex: {
    flex: 1,
    minHeight: 0,
  },
  messagesList: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(3),
    flexGrow: 1,
  },
  emptyText: {
    color: LLM.muted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    paddingVertical: spacing(10),
    paddingHorizontal: spacing(4),
  },
  bubble: {
    maxWidth: '90%',
    marginBottom: spacing(2),
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(2),
    borderRadius: radius.md,
    overflow: 'hidden',
  },
  bubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#1e293b',
  },
  bubbleAssistant: {
    alignSelf: 'flex-start',
    width: '100%',
    maxWidth: '100%',
    backgroundColor: LLM.surface,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  bubbleWithTable: {
    maxWidth: '100%',
  },
  bubbleRefused: {
    borderColor: '#f59e0b',
    backgroundColor: '#fffbeb',
  },
  bubbleText: {
    fontSize: 14,
    lineHeight: 21,
    color: LLM.ink,
  },
  bubbleTextUser: {
    color: '#fff',
  },
  resultStack: {
    gap: 8,
  },
  composer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    paddingHorizontal: spacing(2),
    paddingTop: spacing(2),
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    backgroundColor: LLM.surface,
  },
  input: {
    flex: 1,
    minHeight: 48,
    maxHeight: 120,
    borderWidth: 1.5,
    borderColor: LLM.inputBorder,
    borderRadius: 14,
    paddingHorizontal: spacing(2.5),
    paddingVertical: Platform.OS === 'ios' ? spacing(2.5) : spacing(2),
    fontSize: 15,
    lineHeight: 20,
    color: LLM.ink,
    backgroundColor: LLM.inputBg,
    textAlignVertical: 'top',
  },
  micBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LLM.micBg,
    marginBottom: 2,
  },
  micBtnRecording: {
    backgroundColor: LLM.micRecordingBg,
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LLM.sendBg,
    marginBottom: 2,
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
  tableBlock: {
    width: '100%',
    gap: 8,
    overflow: 'hidden',
  },
  tableToolbar: {
    gap: 8,
  },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: LLM.border,
    backgroundColor: LLM.surface,
    marginRight: 6,
  },
  chipActive: {
    backgroundColor: LLM.ink,
    borderColor: LLM.ink,
  },
  chipText: {
    fontSize: 12,
    color: LLM.ink,
    fontWeight: '600',
  },
  chipTextActive: {
    color: LLM.headerInk,
  },
  dialerBtn: {
    alignSelf: 'flex-end',
    backgroundColor: LLM.ink,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.sm,
  },
  dialerBtnDisabled: {
    opacity: 0.65,
  },
  dialerBtnText: {
    color: LLM.headerInk,
    fontSize: 13,
    fontWeight: '600',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: LLM.header,
  },
  tableHeaderCell: {
    color: LLM.headerInk,
    fontWeight: '600',
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  tableRow: {
    flexDirection: 'row',
    backgroundColor: LLM.surface,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tableRowAlt: {
    backgroundColor: LLM.bg,
  },
  tableCell: {
    color: LLM.ink,
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  voiceOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    zIndex: 30,
  },
  voiceCard: {
    width: '88%',
    maxWidth: 420,
    alignItems: 'center',
    gap: 14,
    paddingHorizontal: 24,
    paddingVertical: 28,
    borderRadius: 20,
    backgroundColor: LLM.header,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.25)',
  },
  voiceLabel: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
    color: '#94a3b8',
  },
  voiceTimer: {
    fontVariant: ['tabular-nums'],
    fontSize: 28,
    fontWeight: '600',
    color: LLM.headerInk,
  },
  voiceHint: {
    fontSize: 13,
    color: '#94a3b8',
    textAlign: 'center',
  },
  voiceStopBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
    minWidth: 132,
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#ef4444',
  },
  voiceStopText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});
