/** Styles for ProfileScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../styles/common';
import { colors, radius, spacing } from '../theme';

export const styles = makeStyles({
  root: { flex: 1, backgroundColor: 'transparent' },
  content: {
    padding: spacing(4),
    paddingBottom: spacing(10),
    gap: spacing(4),
  },
  avatarWrap: { alignItems: 'center', marginTop: spacing(2), marginBottom: spacing(1) },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing(2),
  },
  name: { color: colors.foreground, fontSize: 20, fontWeight: '700' },
  role: { color: colors.muted, fontSize: 13, marginTop: spacing(1) },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(4),
    gap: spacing(3),
  },
  infoRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing(3) },
  infoText: { flex: 1 },
  infoLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  infoValue: { color: colors.foreground, fontSize: 15, marginTop: 2, fontWeight: '600' },
  section: { gap: spacing(2) },
  sectionLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  themeChips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2) },
  themeChip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  themeChipActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  themeChipText: { color: colors.foreground, fontSize: 13, fontWeight: '600' },
  themeChipTextActive: { color: colors.primaryForeground },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(3),
    paddingVertical: spacing(1),
  },
  actionTextWrap: { flex: 1 },
  actionTitle: { color: colors.foreground, fontSize: 15, fontWeight: '600' },
  actionSub: { color: colors.muted, fontSize: 12, marginTop: 2 },
  modalBackdrop: {
    flex: 1,
    justifyContent: 'center',
    padding: spacing(5),
    backgroundColor: 'rgba(0,0,0,0.7)',
  },
  roleModal: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(4),
    gap: spacing(2),
  },
  roleModalTitle: { color: colors.foreground, fontSize: 20, fontWeight: '800' },
  roleModalSub: { color: colors.muted, fontSize: 13, marginBottom: spacing(1) },
  roleOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(3),
  },
  roleOptionActive: { borderColor: colors.primary, backgroundColor: colors.primary },
  roleOptionText: { color: colors.foreground, fontSize: 14, fontWeight: '600' },
  roleOptionTextActive: { color: colors.primaryForeground },
  roleActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing(2),
    marginTop: spacing(2),
  },
  roleCancel: { paddingHorizontal: spacing(4), paddingVertical: spacing(2.5) },
  roleCancelText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  roleSubmit: {
    minWidth: 96,
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2.5),
  },
  roleSubmitText: { color: colors.primaryForeground, fontSize: 14, fontWeight: '800' },
  sosBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(2),
    backgroundColor: colors.destructive,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(4),
  },
  sosBtnActive: { backgroundColor: colors.success },
  sosBtnText: { color: '#fff', fontSize: 14, fontWeight: '800', letterSpacing: 0.4 },
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(2),
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.destructive,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    paddingHorizontal: spacing(4),
  },
  logoutBtnText: { color: colors.destructive, fontSize: 14, fontWeight: '700' },
  version: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: spacing(1),
  },
});
