/** Styles for UserReportScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../styles/common';
import { colors, radius, spacing } from '../theme';

export const styles = makeStyles({
  wrap: { flex: 1 },
  content: { padding: spacing(3), paddingBottom: spacing(8) },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  headerName: { flex: 1, minWidth: 0 },
  title: { color: colors.foreground, fontSize: 18, fontWeight: '700' },
  sub: { color: colors.muted, fontSize: 11, marginTop: 2 },
  muted: { color: colors.muted, fontSize: 12 },
  collapseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    marginBottom: spacing(2),
  },
  collapseTitle: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  collapseChevron: { color: colors.muted, fontSize: 12 },
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  summaryCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
    minWidth: '30%',
    flexGrow: 1,
  },
  summaryCardCompact: { minWidth: '46%' },
  summaryCardClickable: { borderColor: colors.primary },
  summaryCardSuccess: {
    backgroundColor: `${colors.success}10`,
    borderColor: `${colors.success}55`,
  },
  summaryCardError: {
    backgroundColor: `${colors.destructive}10`,
    borderColor: `${colors.destructive}55`,
  },
  summaryLabel: { color: colors.muted, fontSize: 10, marginBottom: 2 },
  summaryValue: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  summaryValueSuccess: { color: colors.success },
  summaryValueError: { color: colors.destructive },
  summaryValueClickable: { textDecorationLine: 'underline' },
  summaryHint: { color: colors.muted, fontSize: 10, marginTop: spacing(1) },
  chipRow: { gap: spacing(2), paddingBottom: spacing(2) },
  chipRowPlain: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  chip: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  filterRow: {
    flexDirection: 'row',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  dateWrap: { flex: 1 },
  input: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.foreground,
    paddingHorizontal: spacing(2),
    paddingVertical: 8,
    fontSize: 13,
  },
  pagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: spacing(2),
  },
  pagerBtn: {
    backgroundColor: colors.surface,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  pagerBtnDisabled: { opacity: 0.4 },
  pagerBtnText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  pagerText: { color: colors.muted, fontSize: 12 },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
    gap: spacing(2),
  },
  formLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  jsonInput: { minHeight: 100, textAlignVertical: 'top' },
  submitBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: spacing(1),
    marginBottom: spacing(2),
  },
  submitBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  chartCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
  },
  chartRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing(1.5) },
  chartLabel: { color: colors.muted, fontSize: 11, width: 92 },
  chartTrack: {
    flex: 1,
    height: 14,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    overflow: 'hidden',
    marginHorizontal: spacing(2),
  },
  chartBar: { height: '100%', borderRadius: radius.sm },
  chartValue: {
    color: colors.foreground,
    fontSize: 11,
    fontWeight: '700',
    width: 76,
    textAlign: 'right',
  },
});
