/** Styles for UsersScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../styles/common';
import { colors, radius, spacing } from '../theme';

export const styles = makeStyles({
  headRow: { flexDirection: 'row', alignItems: 'center' },
  createBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  createBtnText: { color: colors.primaryForeground, fontWeight: '800', fontSize: 13 },
  chipRow: { gap: spacing(2), paddingVertical: spacing(3) },
  chipRowPlain: {
    flexDirection: 'row',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  chip: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
    borderRadius: 999,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  chipText: { color: colors.foreground, fontSize: 12 },
  chipTextActive: { color: colors.primaryForeground, fontWeight: '700' },
  dialerCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing(3),
    marginBottom: spacing(3),
    overflow: 'hidden',
  },
  dialerToggle: {
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(3),
  },
  dialerToggleText: {
    color: colors.primary,
    fontWeight: '700',
    fontSize: 13,
  },
  dialerBody: {
    paddingHorizontal: spacing(3),
    paddingBottom: spacing(3),
    gap: spacing(2),
  },
  dialerRow: {
    flexDirection: 'row',
    gap: spacing(2),
    alignItems: 'center',
  },
  dialerInput: {
    flex: 1,
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.foreground,
    paddingHorizontal: spacing(2),
    paddingVertical: 8,
    fontSize: 13,
  },
  dialerBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
    paddingVertical: 10,
    paddingHorizontal: spacing(3),
    alignItems: 'center',
  },
  dialerBtnDisabled: {
    opacity: 0.45,
  },
  dialerBtnText: {
    color: colors.primaryForeground,
    fontWeight: '700',
    fontSize: 13,
  },
  dialerMsg: {
    color: colors.muted,
    fontSize: 12,
  },
  cardList: {
    marginTop: spacing(3),
    gap: spacing(2),
  },
  cardEmpty: {
    color: colors.muted,
    textAlign: 'center',
    paddingVertical: spacing(6),
    fontSize: 13,
  },
  cardHint: {
    color: colors.muted,
    fontSize: 11,
    textAlign: 'center',
    marginTop: spacing(1),
  },
  userCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
    gap: spacing(3),
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(245, 179, 1, 0.15)',
    borderWidth: 1,
    borderColor: 'rgba(245, 179, 1, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarBlocked: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  avatarText: {
    color: colors.primary,
    fontWeight: '800',
    fontSize: 16,
  },
  avatarTextBlocked: {
    color: colors.destructive,
  },
  userCardMid: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userCardName: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 14,
  },
  userCardNameLink: {
    color: colors.foreground,
  },
  userCardSub: {
    color: colors.muted,
    fontSize: 12,
  },
  userCardTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing(1.5),
    marginTop: spacing(1),
  },
  tagApp: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: colors.border,
    maxWidth: '100%',
    flexShrink: 1,
  },
  tagState: {
    maxWidth: '72%',
  },
  tagAppText: {
    color: colors.foreground,
    fontSize: 10,
    fontWeight: '700',
    flexShrink: 1,
  },
  tagStatus: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderWidth: 1,
    flexShrink: 0,
  },
  tagActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderColor: 'rgba(34, 197, 94, 0.4)',
  },
  tagBlocked: {
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  tagStatusText: {
    fontSize: 10,
    fontWeight: '700',
  },
  tagActiveText: {
    color: colors.success,
  },
  tagBlockedText: {
    color: colors.destructive,
  },
  userCardRight: {
    alignItems: 'flex-end',
    gap: 2,
    flexShrink: 0,
  },
  userCardBalance: {
    color: colors.foreground,
    fontWeight: '700',
    fontSize: 13,
  },
  userCardIdx: {
    color: colors.muted,
    fontSize: 10,
  },
  blockBtn: {
    marginTop: spacing(1),
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.5)',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  blockBtnText: {
    color: colors.destructive,
    fontSize: 11,
    fontWeight: '700',
  },
  blockBtnUnblock: {
    borderColor: 'rgba(34, 197, 94, 0.5)',
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
  },
  blockBtnUnblockText: {
    color: colors.success,
  },
  callBtnRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(1.5),
  },
  callBtn: {
    backgroundColor: '#ff9f0a',
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2.5),
    paddingVertical: 5,
  },
  callBtnText: {
    color: '#1a1200',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  callConfirmBox: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
    marginVertical: spacing(2),
    gap: spacing(0.5),
  },
  callConfirmLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: spacing(1),
  },
  callConfirmValue: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: spacing(5),
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(4),
  },
  modalTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  modalSub: { color: colors.muted, fontSize: 12, marginTop: spacing(2) },
  modalInput: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    fontSize: 14,
    marginTop: spacing(2),
    minHeight: 44,
  },
  otpInput: { textAlign: 'center', letterSpacing: 4, fontSize: 16 },
  modalActions: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(4) },
  mBtn: {
    flex: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
  },
  mBtnGhost: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
  mBtnGhostText: { color: colors.foreground, fontWeight: '700', fontSize: 13 },
  mBtnPrimary: { backgroundColor: colors.primary },
  mBtnPrimaryText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  disabled: { opacity: 0.6 },
  createWrap: { flex: 1, backgroundColor: colors.background },
  createHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing(4),
    paddingTop: spacing(12),
    paddingBottom: spacing(2),
  },
  createTitle: { color: colors.foreground, fontSize: 18, fontWeight: '700' },
  createClose: { color: colors.muted, fontSize: 20 },
});
