/** Styles for WelcomeScreen — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../styles/common';
import { colors, radius, spacing } from '../theme';

export const styles = makeStyles({
  root: { flex: 1, backgroundColor: 'transparent' },
  content: {
    padding: spacing(4),
    paddingBottom: spacing(10),
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hero: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: 'rgba(245,179,1,0.25)',
    borderRadius: radius.lg,
    overflow: 'hidden',
    justifyContent: 'center',
  },
  heroInner: { alignItems: 'center', paddingHorizontal: spacing(4), paddingVertical: spacing(8) },
  logoRing: {
    borderWidth: 1.5,
    borderColor: 'rgba(245,179,1,0.45)',
    backgroundColor: 'rgba(245,179,1,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing(5),
  },
  welcome: {
    color: colors.foreground,
    fontWeight: '800',
    letterSpacing: 4,
    textAlign: 'center',
    opacity: 0.9,
  },
  brand: {
    color: colors.primary,
    fontWeight: '900',
    letterSpacing: 3,
    marginTop: spacing(2),
    textAlign: 'center',
    maxWidth: '100%',
    textShadowColor: 'rgba(245,179,1,0.45)',
    textShadowRadius: 14,
    textShadowOffset: { width: 0, height: 0 },
  },
  csPanel: {
    marginTop: spacing(3),
    backgroundColor: '#000',
    paddingHorizontal: spacing(5),
    paddingVertical: spacing(2),
  },
  csPanelText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 3,
  },
  roleBadge: {
    marginTop: spacing(5),
    backgroundColor: '#000',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    borderRadius: radius.sm,
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(2),
  },
  roleBadgeText: { color: '#fff', fontSize: 12, fontWeight: '800', letterSpacing: 2 },
  signedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    marginTop: spacing(4),
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  onlineDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#22c55e' },
  signedIn: { color: colors.muted, fontSize: 12 },
  tipCard: {
    marginTop: spacing(3),
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(4),
  },
  tipTitle: { color: colors.foreground, fontSize: 15, fontWeight: '700' },
  tipBody: { color: colors.muted, fontSize: 13, marginTop: spacing(1.5), lineHeight: 19 },
});
