/** Styles for WithdrawalScreen — shared presets from styles/common plus screen-specific keys. */
import { StyleSheet } from 'react-native';
import { makeStyles } from '../styles/common';
import { colors, radius, spacing } from '../theme';

export const styles = makeStyles({
  root: { flex: 1 },
  title: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: spacing(3),
  },
  summaryRow: { marginBottom: spacing(3) },
  summaryChip: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    marginRight: spacing(2),
  },
  summaryChipLabel: { color: colors.muted, fontSize: 11 },
  summaryChipValue: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  statusRow: { marginTop: spacing(3), marginBottom: spacing(3) },
  bulkBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  bulkBtn: {
    backgroundColor: colors.surfaceAlt,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
  },
  bulkBtnText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  chip: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    marginRight: spacing(2),
    backgroundColor: colors.surface,
  },
  chipText: { color: colors.muted, fontSize: 12 },
  chipTextActive: { color: colors.primaryForeground, fontWeight: '700' },
  muted: { color: colors.muted, fontSize: 12, marginBottom: spacing(2) },
  pagerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing(3),
    marginTop: spacing(3),
  },
  pagerBtn: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(3),
    backgroundColor: colors.surface,
  },
  pagerBtnDisabled: { opacity: 0.4 },
  pagerBtnText: { color: colors.foreground, fontSize: 13 },
  pagerText: { color: colors.muted, fontSize: 13 },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: spacing(5),
  },
  modalCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(4),
  },
  modalTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: spacing(2),
  },
  modalSub: { color: colors.muted, fontSize: 12, marginTop: spacing(2), marginBottom: spacing(1) },
  modalErr: { color: colors.destructive, fontSize: 12, marginTop: spacing(2) },
  qrIconRow: { flexDirection: 'row', gap: spacing(3), marginTop: spacing(2) },
  qrIconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  qrIconText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  toolsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: spacing(2),
    marginTop: spacing(2),
  },
  toolInput: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.sm,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    minWidth: 110,
    fontSize: 13,
  },
  beneRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing(2),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  beneText: { color: colors.foreground, fontSize: 13 },
  modalInput: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radius.md,
    color: colors.foreground,
    padding: spacing(2),
    minHeight: 60,
    textAlignVertical: 'top',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: spacing(2),
    marginTop: spacing(4),
  },
  confirmBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(4),
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  validationCard: { maxHeight: '85%' },
  validationList: { marginTop: spacing(2) },
  validationHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing(3),
  },
  validationHeaderMain: { flex: 1 },
  validationSub: {
    color: colors.muted,
    fontSize: 12,
    marginTop: -spacing(1),
    marginBottom: spacing(1),
  },
  validationCheckedAt: { color: colors.muted, fontSize: 11 },
  validationScoreBadge: {
    minWidth: 72,
    borderRadius: radius.md,
    borderWidth: 1,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1.5),
    alignItems: 'center',
  },
  validationScoreBadgePass: { backgroundColor: `${colors.success}18` },
  validationScoreBadgeWarn: { backgroundColor: `${colors.primary}18` },
  validationScoreTop: { color: colors.foreground, fontSize: 20, fontWeight: '800' },
  validationScoreBottom: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  validationItem: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
  },
  validationHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing(2),
  },
  validationNameWrap: { flex: 1, gap: spacing(0.5) },
  validationPointLabel: { color: colors.primary, fontSize: 11, fontWeight: '700' },
  validationName: { color: colors.foreground, fontSize: 13, fontWeight: '700', flex: 1 },
  validationStatusPill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1),
  },
  validationStatus: { fontSize: 12, fontWeight: '700' },
  validationReason: { color: colors.muted, fontSize: 12, marginTop: spacing(1) },
  validationEmptyState: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing(3),
  },
  validationEmptyTitle: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  checkBlock: {
    gap: spacing(2),
    paddingTop: spacing(2),
    marginTop: spacing(0.5),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  metaPanel: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(1),
  },
  metaCols: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  metaCol: {
    flex: 1,
    minWidth: 0,
    paddingHorizontal: spacing(1.5),
    justifyContent: 'flex-start',
  },
  metaColFirst: {},
  metaColLast: {},
  metaColCenter: {
    alignItems: 'center',
  },
  metaDivider: {
    width: StyleSheet.hairlineWidth,
    backgroundColor: colors.border,
    alignSelf: 'stretch',
  },
  metaHeadRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: spacing(1),
    minHeight: 16,
  },
  metaHeadRowCenter: {
    justifyContent: 'center',
  },
  metaHead: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.2,
    flexShrink: 1,
  },
  metaVal: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 16,
  },
  metaValCenter: {
    textAlign: 'center',
    width: '100%',
  },
  metaValSub: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '500',
    marginTop: 1,
    lineHeight: 14,
  },
  metaValEmph: {
    color: colors.primary,
  },
  sectionLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.2,
    width: 78,
  },
  checkGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    minHeight: 36,
  },
  checkActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginLeft: 'auto',
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnOk: {
    backgroundColor: 'rgba(34, 197, 94, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.45)',
  },
  iconBtnCross: {
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  checkBtnDisabled: { opacity: 0.45 },
  checkDoneChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(2),
    minWidth: 0,
  },
  checkSymbol: { fontSize: 14, fontWeight: '800', width: 16, textAlign: 'center' },
  checkDoneName: { color: colors.foreground, fontSize: 12, fontWeight: '500', flexShrink: 1 },
  checkOk: { color: colors.success },
  checkNotOk: { color: colors.destructive },
  beneCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    minHeight: 36,
  },
  beneCardMeta: { flex: 1, minWidth: 0 },
  beneCardValue: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  addBeneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing(1.5),
    paddingHorizontal: spacing(2.5),
  },
  addBeneBtnText: { color: colors.primaryForeground, fontSize: 12, fontWeight: '700' },
  botReportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
    paddingTop: spacing(1),
  },
  botReportMeta: { flex: 1, minWidth: 0 },
  botReportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  botReportBtnText: { color: colors.primaryForeground, fontSize: 12, fontWeight: '700' },
  addBeneCard: { maxHeight: '85%' },
  addBeneHint: {
    color: colors.muted,
    fontSize: 12,
    textAlign: 'center',
    marginBottom: spacing(1),
    lineHeight: 17,
  },
  addBeneSelectedCount: {
    color: '#ff9f0a',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '600',
    marginBottom: spacing(1),
  },
  addBeneList: { maxHeight: 280, marginTop: spacing(1) },
  addBeneItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    paddingVertical: spacing(2),
    paddingHorizontal: spacing(2),
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing(1),
    backgroundColor: colors.surfaceAlt,
  },
  addBeneItemDone: {
    borderColor: 'rgba(34, 197, 94, 0.45)',
    backgroundColor: 'rgba(34, 197, 94, 0.08)',
  },
  addBeneItemSelected: {
    borderColor: 'rgba(255, 159, 10, 0.55)',
    backgroundColor: 'rgba(255, 159, 10, 0.08)',
  },
  addBeneCheck: { fontSize: 14, fontWeight: '700', width: 18 },
  addBeneItemText: { color: colors.foreground, fontSize: 13, flex: 1 },
  midReportBtn: {
    width: 28,
    height: 28,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: 'rgba(255,159,10,0.35)',
    backgroundColor: 'rgba(255,159,10,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
});
