/** Styles for LudoDetailsModal — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../styles/common';
import { StyleSheet } from 'react-native';
import { colors, radius, spacing } from '../../theme';

export const styles = makeStyles({
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: spacing(4),
  },
  sheet: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    maxHeight: '85%',
    overflow: 'hidden',
  },
  sheetScroll: { flexGrow: 0, flexShrink: 1 },
  sheetContent: { padding: spacing(4) },
  title: { color: colors.foreground, fontSize: 17, fontWeight: '800' },
  rtpHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing(3),
    gap: spacing(2),
  },
  refreshBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
  },
  refreshBtnText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  sectionLabel: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: spacing(2),
    marginTop: spacing(1),
  },
  rtpLoader: { marginVertical: spacing(3) },
  rtpList: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    overflow: 'hidden',
    marginBottom: spacing(3),
  },
  rtpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing(2),
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  rtpRowActive: {
    backgroundColor: 'rgba(255,159,10,0.12)',
    borderLeftWidth: 3,
    borderLeftColor: '#ff9f0a',
  },
  rtpRowMain: { flex: 1, minWidth: 0 },
  rtpGameId: { color: colors.foreground, fontSize: 13, fontWeight: '700' },
  rtpGameSub: { color: colors.muted, fontSize: 11, marginTop: 2 },
  rtpValue: { color: colors.primary, fontSize: 15, fontWeight: '800' },
  chipWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    marginBottom: spacing(3),
  },
  chip: {
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(1.5),
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceAlt,
  },
  chipRemove: { backgroundColor: colors.destructive, borderColor: colors.destructive },
  chipRemoveText: { color: '#fff' },
  chipText: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  mutedText: { color: colors.muted, fontSize: 12, marginBottom: spacing(2) },
  box: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(3),
    backgroundColor: colors.surfaceAlt,
  },
  input: { marginBottom: spacing(2.5), backgroundColor: colors.background },
  smallBtn: { height: 40, alignSelf: 'flex-start' },
  removeBtn: { height: 40, alignSelf: 'flex-start', backgroundColor: colors.destructive },
  btnRow: { flexDirection: 'row', gap: spacing(2) },
  confirmRow: { gap: spacing(2), marginTop: spacing(1) },
  confirmText: { color: colors.foreground, fontSize: 13, fontWeight: '600' },
  message: { marginTop: spacing(1), fontSize: 12, fontWeight: '600' },
  msgError: { color: colors.destructive },
  msgOk: { color: colors.success },
  footerBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: spacing(2),
    paddingHorizontal: spacing(4),
    paddingVertical: spacing(3),
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  footerBtn: { height: 40 },
});
