/** Styles for ResponsiveTable — shared presets from styles/common plus screen-specific keys. */
import { makeStyles } from '../../styles/common';
import { colors, radius, spacing } from '../../theme';

export const styles = makeStyles({
  list: { marginTop: spacing(2), gap: spacing(2) },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    paddingVertical: spacing(2.5),
    paddingHorizontal: spacing(3),
  },
  cardCompact: {
    paddingVertical: spacing(2.25),
    paddingHorizontal: spacing(3),
  },
  footerCard: { borderColor: colors.primary },
  stateCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: spacing(4),
    marginTop: spacing(3),
  },
  cardRow: { flexDirection: 'row', alignItems: 'center' },
  cardMain: { flex: 1, paddingRight: spacing(2) },
  cardRight: { alignItems: 'flex-end', gap: spacing(1) },
  cardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing(1.5),
  },
  cardTopActions: { flexDirection: 'row', alignItems: 'center', gap: spacing(1) },
  indexPill: {
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(1.5),
    paddingVertical: 3,
  },
  indexPillText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  cardHint: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing(2),
    marginBottom: spacing(1.5),
  },
  titleWithSuffix: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1.5),
  },
  cardTitle: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.1,
    marginBottom: spacing(1.5),
  },
  cardTitleFlex: {
    flex: 1,
    marginBottom: 0,
    minWidth: 0,
  },
  statusPill: {
    backgroundColor: colors.muted,
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: 4,
    maxWidth: '46%',
    alignSelf: 'flex-start',
  },
  statusPillText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  cardSub: { color: colors.muted, fontSize: 11, marginTop: 2 },
  cardFooter: { marginTop: spacing(2) },
  metaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(2),
    paddingTop: spacing(0.5),
  },
  metaItem: {
    flexGrow: 1,
    flexBasis: '30%',
    minWidth: 96,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    paddingHorizontal: spacing(2.5),
    paddingVertical: spacing(1.5),
  },
  metaLabel: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 3,
  },
  metaValue: { color: colors.foreground, fontSize: 13, fontWeight: '600' },
  rowNo: { color: colors.muted, fontSize: 11 },
  fieldGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  field: { width: '50%', paddingRight: spacing(2), marginBottom: spacing(2) },
  fieldLabel: { color: colors.muted, fontSize: 10, marginBottom: 2 },
  fieldValue: { color: colors.foreground, fontSize: 12 },
  fieldSub: { color: colors.muted, fontSize: 10, marginTop: 1 },
  fullHead: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  actionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2), marginTop: spacing(2) },
  actionBtn: {
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1),
  },
  actionBtnText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  editChip: {
    backgroundColor: `${colors.primary}22`,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(1),
  },
  editChipText: { color: colors.primary, fontSize: 12, fontWeight: '700' },
  compactEdit: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactEditText: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  badge: {
    borderRadius: radius.sm,
    paddingHorizontal: spacing(2),
    paddingVertical: spacing(0.5),
    alignSelf: 'flex-start',
  },
  badgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  link: { color: colors.primary, textDecorationLine: 'underline' },
  spinner: { marginVertical: spacing(4) },
  empty: { color: colors.muted, textAlign: 'center', marginVertical: spacing(4) },
});
