import { makeStyles } from '../../../../styles/common';
import { colors, radius, spacing } from '../../../../theme';

export const ggrAlertStyles = makeStyles({
  addBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  addBtnText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  section: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginTop: spacing(3),
  },
  collapseHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(1),
  },
  collapseTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  collapseSummary: { color: colors.muted, fontSize: 12, marginTop: 2 },
  enabledRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    padding: spacing(2),
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    marginBottom: spacing(2),
  },
  enabledTitle: { color: colors.foreground, fontWeight: '700', fontSize: 13 },
  enabledSub: { color: colors.muted, fontSize: 11, marginTop: 2 },
  fieldLabel: { color: colors.muted, fontSize: 11, fontWeight: '600', marginTop: spacing(2) },
  clearLink: { color: colors.destructive, fontSize: 12, fontWeight: '600' },
  clearChip: {
    alignSelf: 'center',
    paddingHorizontal: spacing(1),
    paddingVertical: spacing(1),
  },
  hintLine: {
    color: colors.muted,
    fontSize: 12,
    marginTop: spacing(2),
    marginHorizontal: spacing(3),
    marginBottom: spacing(2),
  },
  dropdownTrigger: {
    marginTop: spacing(1),
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceAlt,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
  },
  dropdownValue: { color: colors.foreground, fontSize: 14, fontWeight: '600' },
  dropdownPreview: { color: colors.muted, fontSize: 11, marginTop: 2 },
  dropdownBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  dropdownBackdropTouch: { flex: 1 },
  dropdownSheet: {
    maxHeight: '78%',
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.lg,
    borderTopRightRadius: radius.lg,
    paddingHorizontal: spacing(4),
    paddingBottom: spacing(4),
    flexShrink: 1,
  },
  dropdownHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    marginVertical: spacing(2),
  },
  dropdownSheetHead: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    marginBottom: spacing(2),
  },
  dropdownSheetTitle: { color: colors.foreground, fontSize: 16, fontWeight: '700' },
  dropdownSheetMeta: { color: colors.muted, fontSize: 12, marginTop: 2 },
  dropdownDoneBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
  },
  dropdownDoneText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  dropdownList: { marginTop: spacing(1), maxHeight: 420 },
  selectedWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing(1.5),
    marginTop: spacing(1.5),
  },
  selectedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(1),
    maxWidth: '100%',
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 999,
    paddingLeft: spacing(2.5),
    paddingRight: spacing(1.5),
    paddingVertical: spacing(1.25),
    backgroundColor: 'rgba(245,179,1,0.12)',
  },
  selectedChipText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    maxWidth: 160,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2),
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    minHeight: 44,
  },
  searchInput: {
    flex: 1,
    color: colors.foreground,
    fontSize: 14,
    paddingVertical: spacing(2.5),
  },
  pickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing(2.5),
    minHeight: 48,
    paddingHorizontal: spacing(1),
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  pickerRowOn: { backgroundColor: 'rgba(245,179,1,0.08)' },
  pickerLabel: { flex: 1, color: colors.foreground, fontSize: 14, fontWeight: '500' },
  pickerLabelOn: { color: colors.primary, fontWeight: '700' },
  input: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    color: colors.foreground,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2.5),
    fontSize: 14,
    marginTop: spacing(1),
  },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(1.5), marginTop: spacing(1) },
  pickChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surfaceAlt,
  },
  pickChipText: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  row: { flexDirection: 'row', gap: spacing(2), marginTop: spacing(3), alignItems: 'center' },
  metaLine: { color: colors.muted, fontSize: 11, marginTop: spacing(2) },
  modeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(1.5), marginTop: spacing(1) },
  modeBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing(3),
    paddingVertical: spacing(2),
    backgroundColor: colors.surfaceAlt,
  },
  modeBtnActive: { borderColor: colors.primary, backgroundColor: 'rgba(245,179,1,0.12)' },
  modeBtnText: { color: colors.muted, fontWeight: '700', fontSize: 12 },
  modeBtnTextActive: { color: colors.primary },
  formBtn: {
    flex: 1,
    borderRadius: radius.md,
    paddingVertical: spacing(3),
    alignItems: 'center',
    justifyContent: 'center',
  },
  formBtnGhost: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
  formBtnGhostText: { color: colors.foreground, fontWeight: '700', fontSize: 13 },
  formBtnPrimary: { backgroundColor: colors.primary },
  formBtnPrimaryText: { color: colors.primaryForeground, fontWeight: '700', fontSize: 13 },
  btnDisabled: { opacity: 0.5 },
  card: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: spacing(3),
    marginBottom: spacing(2),
  },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing(1) },
  cardIndex: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  cardTitle: { color: colors.foreground, fontSize: 15, fontWeight: '700' },
  cardMeta: { color: colors.muted, fontSize: 12, marginTop: 2 },
  typePill: {
    fontSize: 10,
    fontWeight: '700',
    textTransform: 'capitalize',
    color: colors.primary,
    backgroundColor: 'rgba(245,179,1,0.12)',
    paddingHorizontal: spacing(1.5),
    paddingVertical: 2,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing(2), marginTop: spacing(1.5) },
  metric: { color: colors.foreground, fontSize: 12, fontWeight: '600' },
  expandBtn: { marginTop: spacing(2) },
  expandBtnText: { color: colors.primary, fontWeight: '700', fontSize: 12 },
  gameRow: {
    marginTop: spacing(1.5),
    paddingTop: spacing(1.5),
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  gameTitle: { color: colors.foreground, fontWeight: '700', fontSize: 13 },
  listHint: { color: colors.muted, fontSize: 13, marginTop: spacing(3), marginBottom: spacing(1) },
  listFooter: { paddingBottom: spacing(8) },
});
